# Basic Operations On Images With OpenCV
Email : <a href='mailto:madani.a@ucd.ac.ma'>madani.a@ucd.ac.ma</a>
<img src='images/opencv.png'>

### Load Images Using OpenCV

In [1]:
import cv2
# Colored Image
img1 = cv2.imread("messi5.jpg",1)
#Black and White Image (Gray Scale)
img2 = cv2.imread("messi5.jpg",0)
cv2.imshow("couleur",img1)
#cv2.imshow("niveaux de gris",img2)
cv2.waitKey()
cv2.destroyAllWindows()
cv2.waitKey(1) #For Mac only

-1

#### Explications
Dans cet exemple, nous avons :
<ul>
    <li>importé le module OpenCV</li>
    <li>fait la lecture d'une image couleur (RGB). Le chemin complet de l'image (sous forme absolue ou relative) doit être fournit</li>
    <li>fait la lecture d'une image en noir et blanc (en niveaus de gris)</li>
    <li>afficher l'image dans une fenêtre
</ul>    

### Image Shape / Resolution

#### Remarque
Python stocke les images comme des tableaux NumPy, i.e. des matrices de nombres

In [2]:
print(img1)

[[[ 54 121  89]
  [ 54 121  89]
  [ 53 120  88]
  ...
  [ 60 120  89]
  [ 60 120  89]
  [ 60 120  89]]

 [[ 54 121  89]
  [ 54 121  89]
  [ 53 120  88]
  ...
  [ 60 120  89]
  [ 60 120  89]
  [ 60 120  89]]

 [[ 54 121  89]
  [ 54 121  89]
  [ 53 120  88]
  ...
  [ 59 119  88]
  [ 59 119  88]
  [ 59 119  88]]

 ...

 [[ 66 137 104]
  [ 64 135 102]
  [ 55 126  93]
  ...
  [ 50 117  85]
  [ 39 106  74]
  [ 31  98  66]]

 [[ 62 133 100]
  [ 60 131  98]
  [ 53 124  91]
  ...
  [ 49 116  84]
  [ 38 105  73]
  [ 30  97  65]]

 [[ 58 129  96]
  [ 58 129  96]
  [ 51 122  89]
  ...
  [ 47 114  82]
  [ 38 105  73]
  [ 32  99  67]]]


In [3]:
print(img2)

[[104 104 103 ... 104 104 104]
 [104 104 103 ... 104 104 104]
 [104 104 103 ... 103 103 103]
 ...
 [119 117 108 ... 100  89  81]
 [115 113 106 ...  99  88  80]
 [111 111 104 ...  97  88  82]]


In [4]:
print(img1.shape)

(600, 1100, 3)


La taille de la matrice représentant l'image img1 (qui est une image couleur) est 600 lignes, 1100 colonnes et 3 canneaux (Channels). Les trois cannaux représentent les couleurs de bases : RGB

In [5]:
print(img2.shape)

(600, 1100)


La taille de la matrice représentant l'image img2 (qui est une image en noir et blanc) est 600 lignes, 1100 colonnes.

### Display The Image

In [7]:
import cv2
img=cv2.imread("messi5.jpg",0)
cv2.imshow("Messi", img)
cv2.waitKey(2000)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

#### Explications
1. Charge une image. Le deuxième paramètres (0) indique que l'image est en noir et blanc. On peut utiliser la valeur 1 pour charger une image couleur
3. Ouvre une fenêtre pour afficher l'image. Le premier paramètre indique le nom de la fenêtre, alors que le deuxième paramètres précise l'objet image à afficher
5. Attendre un délai. Ici 2000 millisecondes. Si à la place du délai, vous indiquez la valeur 0, la fenêtre sera affichée jusqu'à ce que l'utilisateur presse une touche, comme dans l'exemple suivant.
7. Fermer toutes les fenêtres

In [ ]:
img=cv2.imread("Messi5.jpg",0)

cv2.imshow("Messi", img)

cv2.waitKey(0)

cv2.destroyAllWindows()

On peut indiquer une touche qui sera pressée pour que la fenêtre soit fermée :

In [ ]:
import cv2
img=cv2.imread("Messi5.jpg",0)

cv2.imshow("Messi", img)

key = cv2.waitKey(0)

if key==27 or key==ord('q'):
    cv2.destroyAllWindows()

Dans cet exemple, la fenêtre sera fermée si l'utilisateur appuie sur la touche echappe (code 27) ou la touche 'q'.

### Accès aux pixels d'une image

Dans l'exemple suivant, on va lire le contenu du pixel (0,0) de notre image :

In [ ]:
import cv2

image = cv2.imread('Messi5.jpg')
"""
Lecture du pixel (0,0).
N'oubliez pas que OpenCV utilise l'espace BGR et non pas RGB
b=blue, g=green, r=red
"""
(b, g, r) = image[0,0]
# on affiche les 3 intensites representant notre couleur
print (b,g,r) 
# On change la couleur du pixel (0,0). (255,255,255) :  blanc
image[0,0] = (255,255,255)
#On récupère à nouveau le pixel (0,0)
(b, g, r) = image[0,0]

print (b,g,r) 

cv2.imshow("test", image)

cv2.waitKey(0)

cv2.destroyWindow("test")

<p>
Comme on peut le voir dans l'exemple précédent, l'utilsation de crochets  permet de naviguer dans une image. Ainsi image[0,0] nous renvoie la valeur du pixel situé à la ligne 0 et la colonne 0.
</p>
<p>
Ces crochets peuvent aussi nous permettre de saisir une partie de l'image. Ainsi si on écris image[0:100 , 0:100] cela va retourner un carré de 100 pixels de coté allant du pixel (0,0) au pixel (100,100). Le pixel (0,0) se situe en haut à gauche de notre image et le pixel (100,100) se situe 100 pixels plus à droite et plus à bas.
    </p>

In [ ]:
import cv2
#Chargement d'une image initiale
image = cv2.imread('Messi5.jpg')
#creation d'une autre image à partir de l'image initiale
#Cette nouvelle image, appelée coin, est un carre de 200 pixels de cote
coin = image[0:200, 0:200]
 #affichage des deux images
cv2.imshow("Image Initiale", image)
cv2.imshow("Coin", coin)
# affichage de l'image tant que je n'appuie pas sur une touche
cv2.waitKey(0)
cv2.destroyAllWindows()

On peut utiliser aussi les crochets pour modifier une partie d'une image, comme dans l'exemple suivant :

In [ ]:
import cv2
#Chargement d'une image
image = cv2.imread('Messi5.jpg')
#Taille de l'image. 
height=image.shape[0]
width=image.shape[1]
#Changement de couleur des coins supérieur droit et inférieur gauche
image[0:200, 0:200]=(255, 0,0)
image[height-200:height-1, width-200:width-1]=(0, 0,255)
 #affichage des deux images
cv2.imshow("Image Modifiée", image)
# affichage de l'image tant que je n'appuie pas sur une touche
cv2.waitKey(0)
cv2.destroyAllWindows()

### Resizing The Image
La méthode <b>resize</b> de OpenCV permet de redimensionner une image. Le premier paramètre est l'image à traiter, le deuxième paramètre (tuple) est la nouvelle dimension

In [ ]:
img=cv2.imread("carwash.jpg",0)

resized_img=cv2.resize(img, (600,500))

cv2.imshow("Car Wash", resized_img)

cv2.waitKey(2000)

cv2.destroyAllWindows()

### Explications
Ligne 3 : Change la taille de l'image. Les valeurs (600, 500) représentent les nouvelles dimensions de l'image

### Remarque :
En changeant la taille d'une image avec la méthode <b>resize()</b>, on risque d'avoir une image qui n'est pas symétrique. Une façon de remédier à ce problème est de donner une taille proportionnelle. Par exemple : 

In [ ]:
img=cv2.imread("carwash.jpg",0)

resized_img=cv2.resize(img, (int(img.shape[1]*2),int(img.shape[0]*2)))

cv2.imshow("Car Wash", resized_img)

cv2.waitKey(2000)

cv2.destroyAllWindows()

### Write The Image

Pour enregistrer une image sur le disque, il suffit d'utiliser la méthode <b>imwrite()</b>

In [ ]:
import cv2

img=cv2.imread("carwash.jpg",1)

cv2.imshow("Car Wash", img)

key = cv2.waitKey(0)

if key==27:
    cv2.destroyAllWindows()
elif key==ord('q'):
    cv2.imwrite("carwash.png",img)
    cv2.destroyAllWindows()

### Explications
Après avoir afficher une image avec <b>imshow()</b>, on attend l'utilisateur de taper une touche. La touche echappe ferme la fenêtre, alors que la touche 's', enregistre l'image sous un autre format (ici, format png), puis ferme la fenêtre.

### Dessiner avec OpenCV

<p>
Dans ce paragraphe, nous allons voir comment dessiner des formes plus complexes, comme des cercles, des lignes ou autres formes. Nous allons utiliser pour cela des fonctions d'OpenCV déjà toutes faites : cv2.line(), cv2.rectangle(), cv2.circle().
</p>
<p>
    
cv2.line() demande 5 arguments. Sa syntaxe est la suivante :
    
</p>
<p><center><b>
    cv2.line(canvas, (xstart, ystart), (xend, yend), (blue, green, red), (thickness))</b></center>
</p>
<p>
    où :
<ul>
    <li>canvas est l'image sur laquelle OpenCv doit tracer une ligne</li>

<li>(xstart, ystart) sont les coordonnées du point de départ de notre droite (en pixel)</li>

<li>(xstart, ystart) sont les coordonnées du point d'arrivée de notre droite (en pixel)</li>

<li>(blue, green, red) est la couleur de notre droite</li>

<li>thickness est l'épaisseur de notre ligne (en pixel)</li>
</ul>
</p>
<p>
Par exemple, si on souhaite tracer une droite sur notre image du pixel (0,0) au pixel (100,100) en bleu d'une épaisseur de 1 pixel, on écrira :
</p>
<p>
    <center>cv2.line(image, (0,0), (100,100), (255,0,0), 1)</center>
</p>
<p>
Tout comme cv2.line(), cv2.rectangle demande 5 arguments. Sa syntaxe est donnée comme suit :
</p>
<p><center><b>
    cv2.rectangle(canvas, (xstart, ystart), (xend, yend), (blue, green, red), (thickness))</b></center>
</p>
<p>
    où :
</p>
<p>
    <ul>
        <li>canvas est l'image sur laquelle OpenCv doit tracer un rectangle</li>

<li>(xstart, ystart) sont les coordonnées du point de départ de notre rectangle (en pixel)</li>

<li>(xstart, ystart) sont les coordonnées du point d'arrivée de notre rectangle (en pixel)</li>

<li>(blue, green, red) est la couleur de notre rectangle</li>

<li>thickness est l'épaisseur de notre rectangle(en pixel) (à noter que si vous mettez une épaisser de -1 le rectangle sera rempli)</li>
</ul>
</p>
<p>
Normalement cette fonction ne devrait pas poser trop de problèmes vu qu'elle est quasiment identique à cv2.line().
</p>
<p>
Passons maintenant à cv2.circle(). Elle aussi demande 5 arguments.
</p>
<p><center><b>
    cv2.circle(canvas, (centerx, centery), radius, (blue, green, red), (thickness))</b></center>
</p>
<p>
    <ul>
        <li>canvas est l'image sur laquelle OpenCv doit tracer un rectangle</li>

<li>(centerx, centery) sont les coordonnées du centre de notre cercle (en pixel)</li>

<li>radius est le rayon de notre cercle (en pixel)</li>

<li>(blue, green, red) est la couleur de notre cercle</li>

<li>thickness est l'épaisseur de notre cercle(en pixel) (à noter que si vous mettez une épaisser de -1 le cercle sera rempli)</li>
</ul>
</p>
<p>
Avant de passer à la pratique, nous allons voir comment créer une image entièrement vide. Par entièrement vide, on sous entend que l'image va être complètement noire. Pour cela nous allons utiliser une fonction de la librairie numpy <u>numpy.zeros()</u>. Cette fonction prend deux arguments: les dimensions de l'image à créer et son type (pour nous ce sera toujours uint8).
</p>
<p>
Par exemple : l'instruction numpy.zeros((300,300,3), dtype="uint8"), créée une image carrée de 300 pixels de coté entièrement noire.
</p>    

In [ ]:
import cv2
import numpy as np
image=np.zeros((300,300,3), dtype="uint8")
cv2.line(image,(0,0),(300,300),(255,0,0),1)
cv2.rectangle(image,(150,0),(250,300),(0,255,0),-1)
cv2.circle(image,(150,150), 100,(0,0,255), -1)
cv2.imshow("ImageNoire", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Opération sur les images

<p>Nous allons apprendre dans ce paragraphe comment ajouter deux images en utilisant Python et OpenCV.</p>

<p>Prenons d'abord deux images. Il y a une condition à respecter : les images doivent avoir exactement la même taille.</p>
<p>Voici les images que nous allons utiliser dans nos exemples :</p>
<p><img src="images/road.jpg"></p> et <p><img src="images/car.jpg"></p>

### Ajouter des images
<p>Il existe deux fonctions différentes pour ajouter les images ensemble.
La fonction cv2.add (voir l'exemple ci-dessous) qui ajoute de manière respectivement les pixels de la première image à celle de la seconde.</p>

In [ ]:
import cv2
img_road=cv2.imread("images/road.jpg")
img_car=cv2.imread("images/car.jpg")
img_sum=cv2.add(img_road, img_car)
cv2.imshow("Road", img_road)
cv2.imshow("Car", img_car)
cv2.imshow("Road & Car", img_sum)
cv2.waitKey(0)
cv2.destroyAllWindows()

Cette méthode n'est pas la bonne option lorsque nous voulons ajouter deux images, car elle permet d'ajouter simplement les valeurs ensemble et lorsqu'elles sont 255 ou plus, elles deviennent tout simplement blanches. 

### Ajouter des images pondérées
<p>La première méthode peut être utilisée dans certains cas, mais parfois, nous ne voulons pas effectuer un simple ajout dans l'image. Mais au contraire, nous voulons une sorte de mélange d'images.
</p>
<p>Il s'agit également (dans cette deuxième méthode) d'un ajout d'images, mais différents poids sont attribués aux images afin de donner une impression de fusion ou de transparence. Les images sont ajoutées selon l'équation ci-dessous:
</p>    
<p>
    <center><b>g(x) = (1 - a)f1(x) + af2(x)</b></center>
    </p>
    <p>En faisant varier la valeur de <b>'a'</b> de 0 à 1, vous pouvez effectuer une transition cool entre une image et une autre.</p>
<p>Dans la deuxième méthode, donc, au lieu d'ajouter immédiatement les pixels, on prend également en compte le poids que nous voulons attribuer à chaque image.
</p><p>
On peut attribuer un poids de 0 à 1.
    </p><p>
Par exemple, si nous voulons mettre en surbrillance la voiture et afficher un arrière-plan (la route) doux, nous pourrions attribuer 0.7 à la voiture et 0.3 à l'arrière-plan.</p>

In [ ]:
import cv2
img_road=cv2.imread("images/road.jpg")
img_car=cv2.imread("images/car.jpg")
img_weighted = cv2.addWeighted(img_road, 0.3, img_car, 0.7, 0)
cv2.imshow("Road", img_road)
cv2.imshow("Car", img_car)
cv2.imshow("Road & Car", img_weighted)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Histogramme

Qu'est ce que est un histogramme? On peut considérer un histogramme comme un graphique, ce qui nous donne une idée globale sur la distribution d'intensité d'une image. Il s'agit d'un tracé avec des valeurs de pixels (allant de 0 à 255) sur l'axe X et le nombre correspondant de pixels dans l'image sur l'axe Y.

<p>On peut considérer un histogramme comme une autre façon de comprendre l'image. En regardant un histogramme d'une image, on aura une intuition sur le contraste, la luminosité, la distribution d'intensité, etc. de cette image. Ci-dessous, un exemple d'une image et l'histogramme correspondant :</p>
<p><img src="images/histogram.jpg"></p>

Dans l'image précédente, l'histogramme est dessiné pour une image en niveaux de gris, pas une image en couleur. On peut voir l'image et son histogramme. La région gauche de l'histogramme montre la quantité de pixels qui sont plus sombres dans l'image et la région droite montre la quantité de pixels qui sont plus clairs. À partir de l'histogramme, on peut remarquer que la zone sombre est plus grande que la région qui est plus claire et que la quantité des intensités moyennes (les valeurs des pixels dans la gamme moyenne, disons environ 127) sont très inférieures.

Maintenant que nous avons une idée de ce qu'est un histogramme, nous pouvons voir comment le tracer. OpenCV et Numpy sont livrés avec une fonction intégrée pour cela. Avant d'utiliser ces fonctions, nous devons comprendre certaines terminologies liées aux histogrammes.

<p>
    <b>BINS</b>: l'histogramme ci-dessus montre le nombre de pixels pour chaque valeur de pixel, c'est-à-dire le nombre de pixels pour chaque valeur de 0 à 255. Nous avons besoin donc de 256 valeurs pour afficher l'histogramme ci-dessus. Mais supposons que nous n'avons pas besoin de trouver le nombre de pixels pour toutes les valeurs de pixels séparément, mais le nombre de pixels dans un intervalle de valeurs de pixels. Disons par exemple, nous devons trouver le nombre de pixels pour les plages comprises entre 0 et 15, puis 16 et 31, ..., 240 et 255. Nous n'aurons besoin que de 16 valeurs pour représenter l'histogramme.
</p>
<p>
Donc, ce que nous allons faire c'est tout simplement de diviser tout l'histogramme en 16 sous-parties et la valeur de chaque sous-partie est la somme de tous les pixels. Cette sous-partie est appelée «BIN». BINS est représenté par le terme <b>histSize</b> dans les documents OpenCV.
</p>
<p>
<b>DIMS</b>: C'est le nombre de paramètres pour lesquels nous collectons les données. Dans notre cas, nous collectons des données concernant une seule chose, la valeur d'intensité, d'où la valeur 1.
</p>
<p>
<b>RANGE</b>: C'est la plage de valeurs d'intensité que nous souhaitons mesurer. Normalement, c'est [0,256], c'est-à-dire toutes les valeurs d'intensité.
    </p>

### Histogramme avec OpenCV<p>
Pour tracer un histogramme avec OpenCV, nous utilisons la fonction <b>cv2.calcHist ()</b>. Sa syntaxe est donnée ci-dessous :
</p>
<p><center><b>
cv2.calcHist (images, canaux, masque, histSize, plages [, hist [, accumuler]])
    </b></center></p>
<ul>
<li><b>images</b>: c'est l'image source de type uint8 ou float32. il doit être indiqué entre crochets, c'est-à-dire "[img]".
    <li><b>canaux</b>: il est également indiqué entre crochets. C'est l'indice de canal pour lequel nous calculons l'histogramme. Par exemple, si l'entrée est une image en niveaux de gris, sa valeur est [0]. Pour l'image en couleur, vous pouvez passer [0], [1] ou [2] pour calculer respectivement l'histogramme du canal bleu, vert ou rouge.
    <li><b>mask</b>: masque de l'image. Pour trouver l'histogramme de l'image complète, la valeur de ce paramètre est "None". Mais si nous voulons trouver l'histogramme d'une région particulière de l'image, nous devons créer une image de masque.
    <li><b>histSize</b>: ce paramètre représente le nombre BIN. Il doit être indiqué entre crochets.
    <li><b>range</b>: c'est notre plage. Normalement, c'est [0,256].
    </ul>
Commençons donc par un exemple d'image. Chargeons simplement une image en mode niveaux de gris et trouvons son histogramme complet.

In [ ]:
import cv2
img = cv2.imread ('images/road.jpg', 0)
hist = cv2.calcHist ([img], [0], None, [256], [0,256])
print(hist[0:10])

<b>hist</b> est un tableau 256x1, chaque valeur correspond au nombre de pixels dans cette image avec sa valeur de pixel correspondante.

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt
img = cv2.imread ('images/road.jpg', 0)
hist = cv2.calcHist ([img], [0], None, [256], [0,256])
cv2.imshow("Road", img)
plt.plot(hist)
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()

### Histogramme avec NumPy
<p>
    Numpy fournit également une fonction, <b>np.histogram ()</b>. Ainsi, au lieu de la fonction calcHist (), on peut essayer la ligne ci-dessous:
    </p>
    <center><i>hist,bins = np.histogram(img.ravel(),256,[0,256])</i></center>

In [ ]:
import numpy as np
from matplotlib import pyplot as plt
hist,bins = np.histogram(img.ravel(),256,[0,256])
plt.plot(hist)
plt.show()
print(bins) #Nombre de bins

### Histogramme avec Matplotlib
<p>
    Matplotlib est livré avec une fonction de tracé d'histogramme : <b>matplotlib.pyplot.hist ()</b>

Matplotlib créé directement l'histogramme et le trace. On n'a pas besoin d'utiliser la fonction calcHist () ou np.histogram () pour trouver l'histogramme. Voir le code ci-dessous:
    </p>

In [ ]:
import cv2
from matplotlib import pyplot as plt

img = cv2.imread('images/road.jpg',0)
cv2.imshow("Road", img)
plt.hist(img.ravel(),256,[0,256])
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()

## Threshold

<p>
    Le principe du threshold est simple. Si la valeur d'un pixel est supérieure à une valeur de seuil, une valeur lui est attribuée (par exemple la couleur blanche), sinon une autre valeur (par exemple la couleur noire) lui est affectée. La fonction utilisée est <b>cv2.threshold</b>. 
</p>
<p>Le premier argument de la fonction est l'image source, <u>qui devrait être une image en niveaux de gris</u>. Le deuxième argument est la valeur de seuil qui est utilisée pour classer les valeurs de pixels. Le troisième argument est le maxVal qui représente la valeur à donner si la valeur du pixel est supérieure (parfois inférieure à) la valeur seuil. OpenCV fournit différents styles de seuillage et il est indiqué dans le quatrième paramètre de la fonction. Les différents types sont:</p>
<ul>
    <li>cv2.THRESH_BINARY
    <li>cv2.THRESH_BINARY_INV
    <li>cv2.THRESH_TRUNC
    <li>cv2.THRESH_TOZERO
    <li>cv2.THRESH_TOZERO_INV
    </ul>

In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('images/threshold.jpg',0)
ret,thresh1 = cv2.threshold(img,127,255,cv2.THRESH_BINARY)
ret,thresh2 = cv2.threshold(img,127,255,cv2.THRESH_BINARY_INV)
ret,thresh3 = cv2.threshold(img,127,255,cv2.THRESH_TRUNC)
ret,thresh4 = cv2.threshold(img,127,255,cv2.THRESH_TOZERO)
ret,thresh5 = cv2.threshold(img,127,255,cv2.THRESH_TOZERO_INV)

cv2.imshow("Original Image",img)

cv2.waitKey(0)

cv2.destroyAllWindows()

<img src='images/threshold.jpg'>

## Face and Eyes Detection

<img src="images/face_detection.png">

### Etapes à suivre :
<ol>
    <li><u>Etape 1</u> : Nous avons besoin d'une image, bien sûr. Ensuite il faut créer un classifieur en cascade (Cascade Classifier) qui contient les caractéristiques du visage (et des yeux) qui seront utilisées dans le code pour déterminer le visage et les yeux.
    <li><u>Etape 2</u> : Utiliser OpenCV pour lire une image et le fichier de caractéristiques. L'image sera ensuite convertie en une matrice NumPy. Cette matrice sera utilisée pour connaître les coordonnées du visage et des yeux.
    <li><u>Etape 3</u> : Afficher l'image en encadrant le visage et les yeux par des rectangles.
    </ol>

In [ ]:
import numpy as np
import cv2

face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")

img = cv2.imread("messi5.jpg")

#gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(img, scaleFactor=1.3, minNeighbors=5)

for (x,y,w,h) in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)        
    roi_color = img[y:y+h, x:x+w]
    eyes=eye_cascade.detectMultiScale(roi_color)
    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(roi_color, (ex, ey),(ex+ew, ey+eh),(0,255,0),2)
cv2.imshow('Messi',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Explications
<ol>
    <li> <i>face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")</i> et <i>
        eye_cascade = cv2.CascadeClassifier("haarcascade_eye.xml")</i> : permettent de créer des classifieurs pour détecter le visage et les yeux respectivement.
<li><i>faces = face_cascade.detectMultiScale(img, 1.3, 5)</i> : méthode pour chercher les coordonnées du rectangle délimitant le visage.
<li>L'argument <i>scaleFactor</i> : décroit la valeur de la forme par 5%, jusqu'à ce que le visage soit trouvé. Plus que cette valeur est plus petite, plus que le résultat est meilleur.</li>
<li> <img src="images/rectangle.png">